// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGkFwwt-0gAgkZLPEZp-FytWcUwbOPSRI',
    appId: '1:37439509500:web:47f50c3b4f99a4da975879',
    messagingSenderId: '37439509500',
    projectId: 'fir-demo-16e78',
    authDomain: 'fir-demo-16e78.firebaseapp.com',
    storageBucket: 'fir-demo-16e78.firebasestorage.app',
    measurementId: 'G-HCP4RD8BZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw2gSFANguRB8PvRN_TIH42mP-6UY2gQ8',
    appId: '1:37439509500:android:efa6e07a812d5c71975879',
    messagingSenderId: '37439509500',
    projectId: 'fir-demo-16e78',
    storageBucket: 'fir-demo-16e78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5hu7OTcs0UpxrpesWVtKcwCZZdZPA8CA',
    appId: '1:37439509500:ios:6a02197bc1a3f140975879',
    messagingSenderId: '37439509500',
    projectId: 'fir-demo-16e78',
    storageBucket: 'fir-demo-16e78.firebasestorage.app',
    iosBundleId: 'com.example.onlineGroceriesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5hu7OTcs0UpxrpesWVtKcwCZZdZPA8CA',
    appId: '1:37439509500:ios:6a02197bc1a3f140975879',
    messagingSenderId: '37439509500',
    projectId: 'fir-demo-16e78',
    storageBucket: 'fir-demo-16e78.firebasestorage.app',
    iosBundleId: 'com.example.onlineGroceriesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGkFwwt-0gAgkZLPEZp-FytWcUwbOPSRI',
    appId: '1:37439509500:web:6d445be8ddd9b847975879',
    messagingSenderId: '37439509500',
    projectId: 'fir-demo-16e78',
    authDomain: 'fir-demo-16e78.firebaseapp.com',
    storageBucket: 'fir-demo-16e78.firebasestorage.app',
    measurementId: 'G-9SMWCE9D6K',
  );
}
